export enum InstanceStatus {
  PENDING = 'PENDING',
  SCHEDULING = 'SCHEDULING',
  PROVISIONING = 'PROVISIONING',
  RUNNING = 'RUNNING',
  TERMINATING = 'TERMINATING',
  TERMINATED = 'TERMINATED',
  FAILED = 'FAILED',
}
